### ISSUE TITLE
Unsolicited response without request

### ISSUE THREAD

**Issue by timbell** [michaelherger/MusicArtistInfo#11]
I'm working on a Flutter based client and I'm getting http exceptions (`Unsolicited response without request`) when issuing requests such as: `http://myserver:9000/imageproxy/mai/artist/2881/image.png` .

I've tracked down what I think is the source of the error to the `_getArtistPhotos` method in `ArtistInfo.pm`. It is called with `$services` = `['lfm']` and ends up calling the passed `$cb`  twice. Once in the `if $services{lfm};` case and once in the uncoditional case at the end of the method. Note that the `lfm` case follows a synchronous code path (the artist photo is in a cache) so the unconditional case executes after it.

Shouldn't the unconditional call to `$gotArtistPhotosCb->($results);` at the end of the _`getArtistPhotos` method be moved to the `if ($services{'local'}) {` block? I've tried with this change locally and it does fix the unsolicited response exceptions I've been seeing.

**Comment by michaelherger** [comment]
Could you please point me at those lines? https://github.com/michaelherger/MusicArtistInfo/blob/master/ArtistInfo.pm

**Comment by michaelherger** [comment]
Oh, never mind. Not `$cb` itself is called twice, but `$gotArtistPhotosCb`, which in turn would call `$cb`. Wow, this must have been broken for years... Thanks for the heads up!

**Comment by michaelherger** [comment]
Actually no: https://github.com/michaelherger/MusicArtistInfo/blob/master/ArtistInfo.pm#L335-L336 would make sure we don't call the callback before we have all the results we want. Where would you get that error message you mention? In LMS or in your client? Can you share more information about how you send the request, and what exactly you get back?

**Comment by timbell** [comment]
Yes, that test ensures that all services have completed. In this case there is just the `lfm` service. So the `$gotArtistPhotosCb` callback is called for the `lfm` case and the test passes so `$cb` is called. And then the uncoditional call to `$gotArtistPhotosCb` is made at the end, the test passes again and `$cb` is called again.

I see the error message (`HttpException`) in my Flutter client. I did try executing the http request in Chrome developer tools but it just seems to ignore the unsolicited request. I'll try in Firefox, maybe it'll show up there. Nb I delete `imgproxy.db` to force the error to show up.

**Comment by timbell** [comment]
For clarity, I'm suggesting changing [this](https://github.com/michaelherger/MusicArtistInfo/blob/87834b93870788dd89f6d374edbffb3be16b0937/ArtistInfo.pm#L373-L393) to:
```
	if ($services{'local'}) {
		if (CAN_IMAGEPROXY) {
			my $local = Plugins::MusicArtistInfo::LocalArtwork->getArtistPhoto({
				artist    => $args->{artist},
				artist_id => $args->{artist_id},
			});

			$results->{'local'} = {
				photos => $local ? [{
					url => $local,
					author => cstring($client, 'SETUP_AUDIODIR'),
				}] : [],
			};
		}
		else {
			$results->{'local'}->{photos} = [];
		}
	        $gotArtistPhotosCb->($results);
	}
}
```

**Comment by michaelherger** [comment]
Oh, good reading! Thanks, I'll take care of that. It actually wasn't that bad for years, but only about one year: there were more services before that. And during the cleanup I likely made that mistake.

**Comment by michaelherger** [comment]
Would the following fix your issue?

```diff
diff --git a/ArtistInfo.pm b/ArtistInfo.pm
index 16deb26..8476292 100644
--- a/ArtistInfo.pm
+++ b/ArtistInfo.pm
@@ -363,12 +363,12 @@ sub _getArtistPhotos {
        Plugins::MusicArtistInfo::LFM->getArtistPhotos($client, sub {
                $results->{lfm} = shift || { photos => [] };
                $gotArtistPhotosCb->($results);
-       }, $args ) if $services{lfm};
+       }, $args ) if delete $services{lfm};
 
        Plugins::MusicArtistInfo::Discogs->getArtistPhotos($client, sub {
                $results->{discogs} = shift || { photos => [] };
                $gotArtistPhotosCb->($results);
-       }, $args ) if $services{discogs};
+       }, $args ) if delete $services{discogs};
 
        if ($services{'local'}) {
                if (CAN_IMAGEPROXY) {
@@ -389,7 +389,11 @@ sub _getArtistPhotos {
                }
        }
 
-       $gotArtistPhotosCb->($results);
+       # make sure we call the callback for all defined services
+       foreach (keys %services) {
+               $results->{$_} ||= { photos => [] };
+               $gotArtistPhotosCb->($results);
+       }
 }
 
 sub getArtistPhotoCLI {
```

The previous implementation was wrong, as you proved. But only calling the callback for `local` would be wrong, too, as we don't know what list of services the caller sent. Therefore launch the callback for all of them, even if empty.

**Comment by timbell** [comment]
I'm not sure I understand. I wasn't suggesting only calling the callback in the`local` case but rather calling the callback once per service (as is already the case for `lfm` and `discogs`). All this relying on the test in `$gotArtistPhotosCb` so that `$cb` is only called once. My proposed change seemed more in keeping with the existing logic?

**Comment by michaelherger** [comment]
The previous implementation was already flawed: the caller can pass a list of services to use. But there's no check there aren't more than we have handlers for. Which means that a caller passing a list could have caused the routine to never call back. By adding that loop at the end I'm making sure we call `$cb`, even if no handler had been defined for a service.

Did you give it a try?

**Comment by timbell** [comment]
I have tried it now and it does work. I don't find it very intuitive, tbh - I'm troubled by the lack of symmetry between the `lfm` & `discogs` cases vs `'local`.

An alternative might be to sanitize the input so we only have known services and handle the case where we have no known services explicitly at the top of the method ?

**Comment by michaelherger** [comment]
Not intuitive in a code reading context? Might be that I'm optimizing for the low maintenance case rather than readability... the way I (hopefully correctly) did it now I don't have to maintain a list of services. I must admit that I'd probably vote against this in my job, too. But in case of this plugin I unfortunately have to fight lack of spare time 😞.

**Comment by timbell** [comment]
Absolutely - thanks for dealing with it so swiftly!
